site_name: Git and GitHub CI/CD Workshop
site_description: NHS Data Science Workshop - Git and GitHub CI/CD
site_author: Joseph Wilson - NHS England - Data Science and Applied AI Team
site_url: https://nhsengland.github.io/git-and-github-cicd-workshop
repo_url: https://github.com/nhsengland/git-and-github-cicd-workshop
repo_name: git-and-github-cicd-workshop
edit_uri: edit/main/docs/content/
docs_dir: docs/content

theme:
  name: material
  language: en
  custom_dir: docs/overrides
  palette:
    scheme: default
    primary: indigo
  font:
    text: Roboto
  logo: images/logo/nhs-blue-on-white.jpg
  favicon: images/favicon/favicon.ico
  features:
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - navigation.top
    - toc.integrate
  icon:
    admonition:
      <type>: material/alert

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Workshop Presentation:
    - workshop_presentation/index.md
    - Who am I: workshop_presentation/who_am_i.md
    - Workshop Context: workshop_presentation/workshop_context.md
    - Opinions and Disclaimers: workshop_presentation/opinions_and_disclaimers.md
    - Open Up The Repository: workshop_presentation/open_up_the_repository.md
    - What are Pre-Commit Hooks?: workshop_presentation/pre_commits.md
    - What is GitHub Actions?: workshop_presentation/github_actions_intro.md
  - Workshops:
    - workshops/index.md
    - Pre-Commit Hooks: workshops/pre-commit-hooks.md
    - GitHub Actions: workshops/github_actions.md

extra_css:
  - stylesheets/nhs_style.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nhsengland/git-and-github-cicd-workshop
    - icon: fontawesome/solid/envelope
      link: mailto:datascience@nhs.net
  generator: false

copyright: Copyright &copy; 2025 Crown Copyright (NHS England)

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde

extra_javascript:
  - javascripts/mermaid.mjs

watch:
  - docs/overrides
